// Auto-generated - DO NOT EDIT
// Generated by: pnpm blog:build
// Source: blog-content/book-of-james.md

import type { BlogPost } from '../../types/blog'

export const bookOfJames: BlogPost = {
  title: "The Book of James",
  slug: "book-of-james",
  excerpt: "Join us for a combined 10-day, 5-week journey through the book of James. Each week you'll spend just 15 minutes a day for five days diving into a book that speaks with purpose and direction.",
  featuredImage: "/images/blog/book-of-james.jpg",
  category: "Bible Study",
  publishDate: "2024-02-01",
  author: "JH Outback Team",
  tags: ["bible study","james","scripture"],
  content: `<h2 class="text-2xl font-bold text-primary mt-10 mb-4">About This Study</h2>
<p class="text-gray-600 my-4">Join us for a combined 10-day, 5-week journey through the book of James. Each week you'll spend just 15 minutes a day for five days diving into a book that speaks with purpose and direction.</p>
<h2 class="text-2xl font-bold text-primary mt-10 mb-4">Why James?</h2>
<p class="text-gray-600 my-4">The Book of James is one of the most practical books in the New Testament. Written by James, the brother of Jesus, it challenges believers to live out their faith through action. It's direct, challenging, and transformative.</p>
<h2 class="text-2xl font-bold text-primary mt-10 mb-4">Study Format</h2>
<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>Duration:</strong> 5 weeks</span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>Daily Commitment:</strong> 15 minutes</span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>Days per Week:</strong> 5 days</span></li>
</ul>
<h2 class="text-2xl font-bold text-primary mt-10 mb-4">Weekly Breakdown</h2>
<h3 class="text-xl font-bold text-primary mt-8 mb-4">Week 1: Trials and Temptations (James 1:1-18)</h3>
<p class="text-gray-600 my-4">Learn how to face trials with joy and understand the difference between testing and temptation.</p>
<h3 class="text-xl font-bold text-primary mt-8 mb-4">Week 2: Faith and Works (James 1:19-2:26)</h3>
<p class="text-gray-600 my-4">Discover what it means to be a doer of the word and not just a hearer.</p>
<h3 class="text-xl font-bold text-primary mt-8 mb-4">Week 3: Taming the Tongue (James 3:1-18)</h3>
<p class="text-gray-600 my-4">Explore the power of words and the wisdom that comes from above.</p>
<h3 class="text-xl font-bold text-primary mt-8 mb-4">Week 4: Humility and Submission (James 4:1-17)</h3>
<p class="text-gray-600 my-4">Understand the source of conflict and learn to submit to God's will.</p>
<h3 class="text-xl font-bold text-primary mt-8 mb-4">Week 5: Patience and Prayer (James 5:1-20)</h3>
<p class="text-gray-600 my-4">Conclude with lessons on patience, prayer, and restoring others.</p>
<h2 class="text-2xl font-bold text-primary mt-10 mb-4">How to Join</h2>
<p class="text-gray-600 my-4">Contact us to get connected with a study group or download the study guide to work through it on your own.</p>`,
}

export default bookOfJames
