// Auto-generated - DO NOT EDIT
// Generated by: pnpm blog:build
// Source: blog-content/five-step-prayer-model.md

import type { BlogPost } from '../../types/blog'

export const fiveStepPrayerModel: BlogPost = {
  title: "The 5 Step Prayer Model",
  slug: "five-step-prayer-model",
  excerpt: "John Wimber's practical, Spirit-led approach to praying for others. A five-step model for healing prayer rooted in listening to the Holy Spirit and the ministry of Jesus.",
  featuredImage: "https://cdn.jhoutbacksd.com/blog/5-step-prayer-model-john-wimber.png",
  category: "Prayer",
  publishDate: "2026-04-07",
  author: "Vineyard Resources",
  tags: ["prayer","healing","John Wimber","Vineyard"],
  subtitle: "A Vineyard Approach to Praying for Others",
  content: `<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600"><strong>Disclaimer:</strong> This article is not affiliated with JH Outback. It is shared here as a resource for those interested in the Vineyard approach to prayer ministry.</blockquote>

<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600"><strong>A Special Note:</strong> This booklet is written with special attention to John Wimber's book, <em class="text-accent">Power Healing</em>, chapters 9-12, as well as numerous articles, videos, and materials in which Wimber and others address this topic. Please see this booklet as a companion to the more comprehensive explanations of the Vineyard prayer model addressed in <em class="text-accent">Power Healing</em> (John Wimber and Kevin Springer), <em class="text-accent">Power Evangelism</em> (John Wimber and Kevin Springer), and <em class="text-accent">Power Points</em> (John Wimber and Kevin Springer).</blockquote>

<a href="https://cdn.jhoutbacksd.com/fileshare/5-Step-Prayer-Model-no-images.pdf" target="_blank">Download the 5 Step Prayer Model (PDF)</a>

<p class="text-gray-600 my-4">---</p>

<h2 class="text-2xl font-bold text-primary mt-10 mb-4">Foreword</h2>

<p class="text-gray-600 my-4">One of the most important distinctives of the Vineyard movement is captured in a simple, four-word phrase: "Everyone gets to play." Coined by our founder John Wimber, and based on his understanding of the New Testament call to equip <em class="text-accent">all</em> the saints for the work of ministry (Eph. 4:12), this phrase set the stage for the unique Vineyard approach to compassionately praying for others that is the topic of this booklet.</p>

<p class="text-gray-600 my-4">John believed that every man, woman, and child who is willing to be used by God <em class="text-accent">can learn to hear His voice</em>. As we learn to hear God's voice, we can be led by the Spirit as we minister to others through personal prayer -- rather than relying on our own limited experience or insight. Wimber also taught that any person can <em class="text-accent">cultivate</em> one's ability to hear God's voice over time and through experience, thereby increasing our opportunities to partner with Christ in seeing lives changed, bodies healed, emotions restored to health, and people experiencing the radical, personal love that God uniquely has for <em class="text-accent">them</em>.</p>

<p class="text-gray-600 my-4">Wimber was recognized by the Church of the 20th and 21st centuries, across the world, for his healing ministry. He was known particularly for his low-hype, thoughtful, practical, authoritative, and matter-of-fact approach to operating in the gifts of the Spirit. The Vineyard grew, in part, as God used John powerfully in the ministry of healing. It became normal to hear testimonies of many who experienced physical, emotional, and mental healing in connection with John's ministry. In his eyes, however, it was God doing the healing -- not him -- and God wanted <em class="text-accent">every</em> Christian engaged in praying for others.</p>

<p class="text-gray-600 my-4">John resisted the notion that some of us are called to be spiritual superstars, while others are just ordinary Christians. He was passionate about teaching believers to "do the stuff" of ministry, offering practical approaches to prayer that de-mystified spiritual experience and power ministry. John knew that if ordinary folks learned how to allow the Holy Spirit to guide their prayers for others, Jesus would be made famous around the globe.</p>

<p class="text-gray-600 my-4">In his vital work on the topic, <em class="text-accent">Power Healing</em>, John wrote these words:</p>

<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">"...Shortly after I saw my first healing, I asked myself, 'Is it possible to develop a model for healing from which large numbers of Christians may be trained to heal the sick?' I thought the answer was yes and became committed to developing that model" (<em class="text-accent">Power Healing</em>, p. 169).</blockquote>

<p class="text-gray-600 my-4">This booklet captures the essence of Wimber and the Vineyard's approach to praying for others for <em class="text-accent">all</em> forms of healing, and is designed to be a tool of ministry in your hands as you learn how to effectively pray for others. The principles in these pages are backed by thousands of stories of miraculous encounters, physical healings, emotional transformations, remarkable acts of forgiveness, revelatory moments, demonic deliverances, and restorations of myriad lives to "the joy of the Lord" (Neh. 8:10b).</p>

<p class="text-gray-600 my-4">While the principles in this booklet often speak directly to prayer for physical healing, they apply to any prayer ministry situation we find ourselves in. It is our hope this tool will serve you and your community as you pray, with effectiveness and long-term fruit, for the people that God so loves (John 3:16).</p>

<p class="text-gray-600 my-4">---</p>

<h2 class="text-2xl font-bold text-primary mt-10 mb-4">Wimber on Prayer Ministry</h2>

<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">"The issue is dependence on the Spirit. If there's any pattern, it is simply this -- depend on Him. Depend on Him. Depend on Him. Keep checking back with Him. Don't jump to conclusions. Don't try to recapitulate yesterday's experience."</blockquote>

<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">"Several biblical methods can aid Christians in praying for the sick. I developed a procedure through trial and error that I call 'five steps to healing prayer.' Each element is based on Jesus' method of praying for the sick."</blockquote>

<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">"You won't get a very good effect if you pray generally. You need to pray specifically if you want to be effective in your prayers."</blockquote>

<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">"Jesus used a show, tell, deploy, and supervise method of training. After calling the disciples he took them along with him, teaching and healing the sick as he went."</blockquote>

<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">"The most effective way to train and equip people is by providing effective models and opportunities to practice the skill itself."</blockquote>

<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">"I asked myself, 'Is it possible to develop a model for healing from which large numbers of Christians may be trained to heal the sick?' I thought the answer was yes and became committed to developing that model."</blockquote>

<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">"Learning to pray for the sick is like learning to ride a bicycle. At first the parent runs alongside the wobbly child to prevent serious injury. ...Soon he will learn to ride smoothly and safely. Learning to pray for the sick is a similar process: the first solo experiences are usually messy, but in time they become quite enjoyable. I am more interested in ministry than neatness, so I provide a place in which people know they are accepted and helped even when they fail."</blockquote>

<em class="text-accent">-- Wimber quotes from Power Healing & teaching on The 5 Step Healing Model</em>

<p class="text-gray-600 my-4">---</p>

<h2 class="text-2xl font-bold text-primary mt-10 mb-4">The 5 Step Prayer Model: An Introduction</h2>

<h3 class="text-xl font-bold text-primary mt-8 mb-4">Pray For A Thousand People, Then We'll Talk</h3>

<p class="text-gray-600 my-4">John Wimber's healing conferences and teaching impacted thousands of Christians around the world in the 20th century. He noted once that he would receive cards or letters after someone had heard him teach that would say something to the effect of, "I went home and prayed for somebody and it didn't work." John would laugh and reply, "Why don't you pray for a <em class="text-accent">thousand</em> somebodies, and then let's talk."</p>

<p class="text-gray-600 my-4">The <em class="text-accent">5 Step Prayer Model</em> is not a scientific formula, fool-proof methodology, or magical incantation. Rather, it is an intentional way of praying for others, from a posture of listening to the Holy Spirit, that provides a track to run on for those desiring to see God move in power as they pray.</p>

<p class="text-gray-600 my-4">While physical healing is often the focus of prayer ministry, in its essence the <em class="text-accent">5 Step Prayer Model</em> is a <em class="text-accent">relational, interactive way of praying for others as we listen to the Holy Spirit</em> -- a process that begins and ends with mercy toward the person requesting prayer, and that seeks both God's will and God's best for the person being prayed for. It is also relational in the sense that we are leaning heavily on our intimate relationship with God as we pray for someone, welcoming Him to speak insights into our hearts or minds that would directly impact the person being prayed for. Vineyard churches around the world have a reputation for being places where compassionate, Spirit-guided prayer ministry can be received. For us, prayer ministry can happen in a church service, in a mechanic's garage, in a hospital room, or over a backyard fence.</p>

<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600"><em class="text-accent">"The five-step procedure may be used any time and in any place: in hotels, at neighbors' homes, on airplanes, at the office, and, of course, in church gatherings. I have been in casual conversation with people, even with complete strangers, who mention some physical condition, and I ask, 'May I pray for you?' Rarely do they decline healing prayer, even if they are not Christians. I then confidently pray for them by following the five-step method"</em> (Wimber, <em class="text-accent">Power Healing</em>).</blockquote>

<p class="text-gray-600 my-4">The basis for the approach in the following pages is the model of Jesus as he ministered to the sick. It also draws on Wimber's experience as he witnessed thousands of people encounter God's love through signs, wonders, and dramatic healings.</p>

<p class="text-gray-600 my-4">Over time, and with practice, this way of praying for people is meant to become internalized. As we begin to see patterns when we pray for certain types of people or issues, we grow in our ability to hear God's voice as we are praying. We may begin to experience the Holy Spirit giving us spiritual gifts as we pray. What we thought in the past were random impressions, we actually learn are gifts of revelation from God! We may begin to see people physically or emotionally healed, or at the very least leaving a time of prayer with a deposit of God's love in their heart.</p>

<p class="text-gray-600 my-4">Wimber once said that the worst thing we can do is rely on our past experience when praying for another. Each individual has a unique story, and God has something creative He wants to do. This keeps us humble, attentive, and ready to obey God as He leads us in praying for others.</p>

<p class="text-gray-600 my-4">---</p>

<h2 class="text-2xl font-bold text-primary mt-10 mb-4">Step 1: The Interview</h2>

<strong>Introduce yourself, then ask, "How can I pray for you?" or "Where does it hurt?"</strong>

<p class="text-gray-600 my-4">In this first step, we introduce ourselves to the person, and ask the questions "How can I pray for you?" or "Where does it hurt?"</p>

<p class="text-gray-600 my-4">This is not a medical interview or a counseling session, but rather an opportunity to listen as we assess the person's situation and need. This step ensures that the person feels valued, and gives us an opportunity to listen to God and the individual before any prayer begins. It also enables us to hear how the person perceives his or her condition before jumping to any conclusions.</p>

<p class="text-gray-600 my-4">According to Wimber, we are listening to the person on two levels at this point. On a <em class="text-accent">natural</em> (empirical) level, we are hearing the request. On a <em class="text-accent">supernatural</em> level, we are listening simultaneously for God to speak to us about the person and/or the situation. Based on what we are seeing and hearing, as well as on past patterns we may recognize from praying for similar types of people or conditions, we can begin to assess how God might be leading us to pray. However, we must not be dependent on our past experiences, but rather on God. Even as a person is speaking, the Holy Spirit may begin to give you pictures, scriptures, or other insights. In this case, it is not always necessary to have the person continue. Go right to prayer, as God may have another agenda that He wants to see fulfilled.</p>

<p class="text-gray-600 my-4">As we become increasingly sensitive and responsive to the Spirit's presence over years of practice (Wimber suggested 40 or 50 years to start!), we become open for the Spirit to give us spiritual gifts for ministry. During the interview, He may want to plant in our minds scriptures, words of knowledge (things we could not have otherwise known), or images (pictures illustrating something God is revealing).</p>

<p class="text-gray-600 my-4">We take our time, are quiet, and listen. Our dependency is on God to make something happen, not on ourselves. He wants to do something beautiful and creative in this person, and loves to use us in the process. Wimber would say, "It's more important to know what kind of person has a bug rather than what kind of bug has a person." In other words, God may want to touch something in the person's life other than the illness or topic of the prayer request! Be open to the Spirit's guidance. If you have no clue what to pray after the interview, then be honest; don't fake it or put on a spiritual persona. Maintain your integrity, and if necessary, just pray for God to bless the person.</p>

<h3 class="text-xl font-bold text-primary mt-8 mb-4">Summary Notes</h3>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">What can you see on a natural level?</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">What do you sense on a supernatural level? Ask God for scriptures, words of knowledge, insights, visions, images</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Just get the facts; not a medical interview or a counseling session</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Move to the next stage when you're ready.</em></span></li>
</ul>
<p class="text-gray-600 my-4">---</p>

<h2 class="text-2xl font-bold text-primary mt-10 mb-4">Step 2: The Diagnosis</h2>

<strong>"Why does this person have this condition?"</strong>

<p class="text-gray-600 my-4">Now we can begin to identify the underlying issue we sense God is inviting us to pray for. We are asking, "Why does this person have this condition (or point of need)?"</p>

<p class="text-gray-600 my-4">There are many reasons someone might need prayer, and if the request is for physical healing, there may be a variety of reasons the person has a condition. The cause of a condition could be:</p>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>a) Disease</strong> (natural causation -- the person is just sick or has had an accident)</span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>b) Sin</strong> (the person has committed a sin, or someone has sinned against them)</span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>c) Emotional hurts</strong> (these can trigger physical symptoms)</span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>d) Relationship problems</strong> (issues of unforgiveness or anger)</span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>e) Demonic influence</strong> (spiritual powers afflicting the person)</span></li>
</ul>
<p class="text-gray-600 my-4">Sometimes you may discern it is a combination of a few of these causes above. This is why we must depend on the Spirit -- we don't want to be praying about one area for a person when the real issue is coming from something else. Our goal is to see the person experience the depths of God's love, and to find freedom and healing in his or her heart, mind, and body. It is important to note here that in the Vineyard we see every person as a precious human being made in the image of God, who has chosen to be vulnerable in this moment of asking for prayer. We never treat people as a project, or with indifference; we dignify people in the process of them seeking God for help. In ministry moments, the highest call of God on us is the second commandment -- to love this person that He loves. Often people may not know the exact root of the problem. What they are asking for prayer about may not be the main issue God wants to address.</p>

<p class="text-gray-600 my-4">Ask the Holy Spirit to confirm if the person's analysis of the situation is accurate, or if there is something else He wants to reveal. People are complex, and the issues affecting their conditions can be just as complex. A marriage may be in pain because of a childhood hurt. Bodies can be afflicted by psychosomatic illness, which is no less real in its impact than a disease. Holding resentment or bitterness toward another (living or dead) can cause distress that impacts a person emotionally and physically. The interview concludes when we have determined what we believe to be the cause of the condition we are praying for.</p>

<h3 class="text-xl font-bold text-primary mt-8 mb-4">Summary Notes</h3>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Are there natural causes here, such as a disease or accident?</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Is there sin involved, committed by the person or against the person?</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Are there emotional hurts causing physical symptoms?</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Are there relationship problems that are part of this issue?</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Is there demonic influence?</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Continue to ask God for help</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Ask more questions if it seems appropriate</em></span></li>
</ul>
<p class="text-gray-600 my-4">---</p>

<h2 class="text-2xl font-bold text-primary mt-10 mb-4">Step 3: Prayer Selection</h2>

<strong>"What kind of prayer is needed to help this person?"</strong>

<p class="text-gray-600 my-4">At this stage we are now asking, "What kind of prayer is needed to help this person?" and "Lord, (what) do you want to heal right now?"</p>

<p class="text-gray-600 my-4">We can assume that God wants to touch this person. However, He may not intend to heal the person in the way he or she desires. We want to agree with God in our prayers, rather than expect God to agree with <em class="text-accent">us</em> on what we want to see happen. Having said this, we confidently pray for healing with 1 John 5:14-15 in mind:</p>

<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600"><em class="text-accent">"This is the confidence we have in approaching God: that if we ask anything according to his will, he hears us. And if we know that he hears us -- whatever we ask -- we know that we have what we asked of him."</em></blockquote>

<p class="text-gray-600 my-4">If we pray too generally, and with timidity, as if God <em class="text-accent">probably</em> doesn't want to do anything (or we don't want to look silly), then we <em class="text-accent">probably</em> won't see much happen. However, if we pray with confidence (without arrogance) and humility (without apology), led by the inner prompting of the Spirit, we are praying with the kind of confidence Jesus spoke of in Mark 11:24.</p>

<p class="text-gray-600 my-4">Wimber suggested that there are two categories into which healing prayers fall:</p>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>Prayers directed toward God</strong></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>Words received from God</strong></span></li>
</ul>
<p class="text-gray-600 my-4">In the first, we are asking God how we should intercede for a sick person or a person requesting prayer. We are in a <em class="text-accent">listening</em> posture. Some choose to pray in tongues (1 Cor. 14:4) to make their hearts attentive and sensitive to God as they wait for insight from the Holy Spirit.</p>

<em class="text-accent">Prayers of intercession</em>, in which we ask God to touch a person and the condition, may be the way the Spirit is inviting us to pray.

<p class="text-gray-600 my-4">Sometimes God wants to speak something <em class="text-accent">through</em> us to the person. We may sense we are to pray <em class="text-accent">prayers of command</em> ("cancer, be gone in Jesus' name"), <em class="text-accent">words of pronouncement</em> ("I sense the Lord has healed you"), <em class="text-accent">prayers of rebuke</em> ("in Jesus' name, I rebuke the enemy" [Mark 9:25]), or <em class="text-accent">prayers of agreement</em> (agreeing with another person on your shared desire to see God's will accomplished [Matt. 18:19-20] in this person's life).</p>

<p class="text-gray-600 my-4">Ask God for wisdom, and believe you'll receive it. Leaning on the Holy Spirit, decide how you will pray, and move toward prayer engagement.</p>

<h3 class="text-xl font-bold text-primary mt-8 mb-4">Summary Notes</h3>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Ask if the person is comfortable with the laying on of hands</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Ask the Holy Spirit to bring healing to the person</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Pray in the Spirit (pray in tongues as able)</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Consider the command of faith (Acts 3:6)</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Consider the pronouncement of faith (John 4:50)</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Consider the rebuke (breaking the power) of demonic influences; binding them (containing), or expelling them (getting rid of)</em></span></li>
</ul>
<p class="text-gray-600 my-4">---</p>

<h2 class="text-2xl font-bold text-primary mt-10 mb-4">Step 4: Prayer Engagement</h2>

<strong>"How effective are our prayers right now?"</strong>

<p class="text-gray-600 my-4">This step consists of us moving into prayer, laying our hands on the person, and asking further interview questions as necessary.</p>

<p class="text-gray-600 my-4">Having decided how we will pray, we move forward, trusting we are sensing what the Father is doing in this person's life. As was noted in the previous step, we lay hands on the person if given permission. If there is a physical spot on the person's body that needs healing, we ask if we can lay hands on that part of the body (Luke 4:40). (When asking if we can lay hands on the person, we are always respectful. Helping him or her to feel safe aids the process.)</p>

<p class="text-gray-600 my-4">If the person is a member of the opposite sex, have someone of their own gender lay hands on them, or involve the spouse or friend. Wimber said, "It's important to treat people with respect so they may maintain their dignity" (<em class="text-accent">Power Healing</em>, p. 211). In some cases, it may seem best to extend one's hands toward the person, rather than touching, especially if someone else is already laying hands on the person.</p>

<p class="text-gray-600 my-4">As we begin, we may want to continually pray a prayer that has become vital in our Vineyard story: <strong>"Come, Holy Spirit."</strong> This prayer is a simple invitation for the Spirit to do the work that only God can do. People may respond to the presence of the Spirit in various ways. They may remain quiet and still as we pray. They may experience warmth, or tingling in an area of the body, as prayer continues. As prayer is a power encounter between the overwhelming love of God and the enemy of our souls, there may be other manifestations such as trembling, shaking, weeping, laughing, or even falling over. When people experience the peace and joy of God, breaking into their dire situation, there may be physical expressions that accompany the experience. Phenomena like these have occurred in revivals throughout church history, and may be one indicator that God's presence is being felt by the person. (Read <em class="text-accent">Power Healing</em>, p. 211-235, for more on manifestations during prayer.)</p>

<p class="text-gray-600 my-4">Continuing to listen to the Spirit as we pray, we ask God to pour more of His love into the person. We listen for revelation from God, and we follow those threads in our prayers. In the Vineyard, we often pray with our eyes open during personal ministry times. This is because we've become aware that some indications of effectiveness can be seen as we pray, while others cannot. When we sense we are finished praying, the person feels we are finished, or we have nothing left to pray, we let the person know we are finishing the prayer.</p>

<h3 class="text-xl font-bold text-primary mt-8 mb-4">Summary Notes</h3>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Keep eyes open and watch for any effect (phenomenological signs like warmth, tingling, shaking)</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Ask questions of the person to find out what God might be doing</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Stop praying when a) they think it's over, b) the Spirit tells you it's over, c) you've run out of things to pray, or d) it's going nowhere</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Remove your hands and talk to them to indicate you are stopping</em></span></li>
</ul>
<p class="text-gray-600 my-4">---</p>

<h2 class="text-2xl font-bold text-primary mt-10 mb-4">Step 5: Post-Prayer Direction</h2>

<strong>"What should this person do to remain healed?" or "What should this person do if he or she was not healed?"</strong>

<p class="text-gray-600 my-4">If the prayer focus is on physical healing, the results of healing prayer can be many. Offering some simple "next step" direction may be helpful.</p>

<p class="text-gray-600 my-4">If the person was healed, or had a significant breakthrough in some area, encourage him or her to continue to walk closely with God, maintaining a rich life of worship, Bible reading, church connection, and avoidance of sin. You can also encourage the person to get the healing confirmed by a medical professional. If a person was not healed, or did not have a significant breakthrough in their area of need, "...reassure them that God loves them and encourage them to seek more prayer" (<em class="text-accent">Power Healing</em>, p. 235).</p>

<p class="text-gray-600 my-4">For healing of the heart, mind, and body to be sustained, even after a moment of divine intervention, environments of committed Christian discipleship, accountability, and spiritual formation are necessary for ongoing growth. If words or scriptures were received that were meaningful, encourage the person to write them down or record them so they can be referred to later.</p>

<p class="text-gray-600 my-4">God's intent in generously giving signs, wonders, miracles of healing, words of encouragement, words of knowledge, prophetic insights, and other gifts of love in times of prayer is that we would be drawn to love Him more, serving Him through a life of complete devotion. Anything we can do to encourage someone to live out the greatest commandment, to <em class="text-accent">"Love the Lord your God with all your heart and with all your soul and with all your mind and with all your strength"</em> (Mark 12:30) is appropriate.</p>

<h3 class="text-xl font-bold text-primary mt-8 mb-4">Summary Notes</h3>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Encourage the person to pursue continued prayer about the issue</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">As necessary, call him or her to cease sinning (John 5:14; 8:11)</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Encourage the person to read the Scriptures and to nurture a deep relationship with God</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Encourage them to stay active in a local church community</em></span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span><em class="text-accent">Visit their doctor, if a healing occurred, to confirm the healing</em></span></li>
</ul>
<p class="text-gray-600 my-4">---</p>

<h2 class="text-2xl font-bold text-primary mt-10 mb-4">The 5 Step Prayer Model Card</h2>

<h3 class="text-xl font-bold text-primary mt-8 mb-4">Principles to Remember</h3>

<strong>01 -- The Interview</strong>
<p class="text-gray-600 my-4">Introduce yourself, then ask, <strong>"How can I pray for you?"</strong> or <strong>"Where does it hurt?"</strong> This is not a medical interview, but rather an opportunity to listen as we assess the person's need.</p>

<strong>02 -- The Diagnosis</strong>
<p class="text-gray-600 my-4">"Why does this person have this condition?" Identify the underlying issue you sense God is inviting you to pray for. It could be physical, emotional, relational, or otherwise.</p>

<strong>03 -- Prayer Selection</strong>
<p class="text-gray-600 my-4">"What kind of prayer is needed to help this person?" You can also ask, "Lord, (what) do you want to heal right now?" Consider prayers of intercession, command, pronouncement, rebuke (of demonic influences), and agreement.</p>

<strong>04 -- Prayer Engagement</strong>
<p class="text-gray-600 my-4">"How effective are our prayers right now?" Move into prayer, laying hands on the person (respectfully and by invitation), and asking further interview questions as necessary. Pray according to your diagnostic decision and prayer selection, listening to the Spirit.</p>

<strong>05 -- Post-Prayer Direction</strong>
<p class="text-gray-600 my-4">"What should this person do to remain healed?" or "What should this person do if he or she was not healed?" Offer some simple direction to the person who was prayed for. Encourage him or her to receive more prayer. Encourage the person to nurture a deep relationship with God, to stay in the Scriptures, to remain in fellowship, and to turn away from sin. If a healing occurred, encourage him or her to get confirmation from a medical professional. Finally, encourage them to document what God did.</p>

<strong>Trust God to use you in prayer -- and expect the Kingdom to come!</strong>

<p class="text-gray-600 my-4">---</p>

<em class="text-accent">Vineyard Resources</em>
<em class="text-accent">Copyright 2016 Vineyard Resources. All rights reserved.</em>

<em class="text-accent">Scriptures taken from the Holy Bible, New International Version (NIV). Copyright 1973, 1978, 1984, 2011 by Biblica, Inc. Used by permission of Zondervan. All rights reserved worldwide.</em>`,
}

export default fiveStepPrayerModel
