// Auto-generated - DO NOT EDIT
// Generated by: pnpm blog:build

import type { BlogPostMeta, BlogPost } from '../../types/blog'

import { writtenTestimony } from './written-testimony'
import { bookOfJames } from './book-of-james'

// All blog posts with full content
export const blogPosts: Record<string, BlogPost> = {
  'written-testimony': writtenTestimony,
  'book-of-james': bookOfJames,
}

// Blog posts metadata only (for listing pages)
export const blogPostsMeta: BlogPostMeta[] = [
  {
    title: "Written Testimony",
    slug: "written-testimony",
    excerpt: "Learn how to share your Christian testimony in 15 minutes or less. This is designed for new or experienced believers to share the life-changing power of your faith.",
    featuredImage: "/images/blog/written-testimony.jpg",
    category: "Testimony",
    publishDate: "2024-01-15",
    author: "JH Outback Team",
    tags: ["testimony","faith","guide"],
    subtitle: "HOW TO PREPARE A 20-minute TESTIMONY - GENERAL OUTLINE",
  },
  {
    title: "The Book of James",
    slug: "book-of-james",
    excerpt: "Join us for a combined 10-day, 5-week journey through the book of James. Each week you'll spend just 15 minutes a day for five days diving into a book that speaks with purpose and direction.",
    featuredImage: "/images/blog/book-of-james.jpg",
    category: "Bible Study",
    publishDate: "2024-02-01",
    author: "JH Outback Team",
    tags: ["bible study","james","scripture"],
  },
]

// Get a single blog post by slug
export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts[slug]
}

// Get all categories
export function getAllCategories(): string[] {
  const categories = new Set(blogPostsMeta.map((post) => post.category))
  return Array.from(categories).sort()
}

// Get all tags
export function getAllTags(): string[] {
  const tags = new Set(blogPostsMeta.flatMap((post) => post.tags))
  return Array.from(tags).sort()
}

export default blogPosts
